/// Activity & Progress Engine — core activity model.
///
/// An [Activity] is a single bout of movement a member did (a walk, a run, a
/// strength session…). It is deliberately independent of the user model and
/// of gym visits: a `CheckIn` records that a member entered a gym, an
/// [Activity] records what they did. The two may share a `gymId`, but a
/// check-in never becomes an activity on its own.
library;

/// What kind of movement an activity was. Wire values are snake_case.
/// The device name saved with steps counted by the phone itself. It is
/// stored data, so it stays as is; screens show it in the app language.
const phoneStepsDeviceName = 'This phone';

enum ActivityType {
  walking('walking'),
  running('running'),
  jogging('jogging'),
  cycling('cycling'),
  hiking('hiking'),
  swimming('swimming'),
  sports('sports'),
  strength('strength'),
  hiit('hiit'),
  functional('functional'),
  groupClass('group_class'),
  personalTraining('personal_training'),
  mobility('mobility'),
  stretching('stretching'),
  other('other');

  const ActivityType(this.wire);

  final String wire;

  /// Unknown or missing values fall back to [other] so newer backends never
  /// break older app builds.
  static ActivityType fromWire(String? value) => values.firstWhere(
    (t) => t.wire == value,
    orElse: () => ActivityType.other,
  );

  /// Movement measured mainly by distance/steps rather than sets and reps.
  bool get isDistanceBased => const {
    walking,
    running,
    jogging,
    cycling,
    hiking,
    swimming,
  }.contains(this);
}

/// Where an activity record came from. This is provenance only — it says
/// nothing about whether a device integration exists (none do yet).
enum ActivitySource {
  /// Synced from a health platform or wearable (Apple Health, Health
  /// Connect, a watch…).
  device('device'),

  /// Tracked inside the FitFlex app itself.
  fitflex('fitflex'),

  /// Typed in by the member.
  manual('manual'),

  /// Logged by a linked trainer.
  trainer('trainer'),

  /// Logged by a gym (e.g. a class roster).
  gym('gym');

  const ActivitySource(this.wire);

  final String wire;

  /// Unknown values fall back to [manual], the least-trusted source.
  static ActivitySource fromWire(String? value) => values.firstWhere(
    (s) => s.wire == value,
    orElse: () => ActivitySource.manual,
  );
}

/// The three kinds of data the member sees, from most to least automatic.
///
/// - [device]: measured by a phone, watch or wearable and synced through a
///   health platform. Only a device provider may create it.
/// - [fitflex]: generated by FitFlex itself, e.g. finishing a workout in
///   the app.
/// - [manual]: entered by a person: the member, their trainer or their gym.
enum DataOrigin { device, fitflex, manual }

/// The health platform or wearable a device record came from.
enum DevicePlatform {
  /// The phone's own step counter, read by FitFlex.
  phoneSensor('phone_sensor'),
  appleHealth('apple_health'),
  healthConnect('health_connect'),
  fitbit('fitbit'),
  garmin('garmin'),
  other('other');

  const DevicePlatform(this.wire);

  final String wire;

  static DevicePlatform? fromWire(String? value) {
    for (final p in values) {
      if (p.wire == value) return p;
    }
    return null;
  }
}

enum ActivityIntensity {
  low('low'),
  moderate('moderate'),
  high('high');

  const ActivityIntensity(this.wire);

  final String wire;

  static ActivityIntensity? fromWire(String? value) {
    for (final i in values) {
      if (i.wire == value) return i;
    }
    return null;
  }
}

class Activity {
  final String id;
  final String userId;
  final ActivityType type;
  final ActivitySource source;
  final DateTime startedAt;

  // Metrics — every one is optional; a strength session has no distance and
  // a device step summary has no workout.
  final int? durationMinutes;
  final double? distanceKm;
  final int? steps;
  final int? activeMinutes;
  final int? calories;
  final ActivityIntensity? intensity;

  // Optional links into the rest of FitFlex.
  final String? workoutId;
  final String? gymId;
  final String? trainerId;

  final String? notes;

  // Device provenance. Set only on device records, by a device provider.
  final DevicePlatform? devicePlatform;

  /// The platform's own record id, so a re-sync updates instead of
  /// duplicating.
  final String? externalId;

  /// e.g. "Apple Watch"; display only.
  final String? deviceName;

  // Runs recorded in the app (GPS).
  final int? movingSeconds;
  final double? elevationGainM;

  /// Seconds for each whole km.
  final List<int> splits;

  /// Whether the member can open this run's (private) route.
  final bool hasRoute;

  /// Who else can see it (`{followers, groups, company}`); null = private.
  final Map<String, dynamic>? shareWith;

  /// Generated demo data. Never sent to the server and never shown as
  /// device, FitFlex or manual data.
  final bool isSample;

  const Activity({
    required this.id,
    required this.userId,
    required this.type,
    required this.source,
    required this.startedAt,
    this.durationMinutes,
    this.distanceKm,
    this.steps,
    this.activeMinutes,
    this.calories,
    this.intensity,
    this.workoutId,
    this.gymId,
    this.trainerId,
    this.notes,
    this.devicePlatform,
    this.externalId,
    this.deviceName,
    this.movingSeconds,
    this.elevationGainM,
    this.splits = const [],
    this.hasRoute = false,
    this.shareWith,
    this.isSample = false,
  });

  /// A run recorded with GPS in the app.
  bool get isRecordedRun =>
      source == ActivitySource.fitflex && movingSeconds != null;

  /// Which of the three kinds of data this is. Trainer and gym records are
  /// manual: a person entered them. A "device" record that doesn't name
  /// its platform can't have come from a device sync, so it's treated as
  /// manual rather than presented as measured.
  DataOrigin get origin => switch (source) {
    ActivitySource.device when devicePlatform != null => DataOrigin.device,
    ActivitySource.fitflex => DataOrigin.fitflex,
    _ => DataOrigin.manual,
  };

  /// A whole day's steps counted by the phone, not a session.
  bool get isDailyStepTotal =>
      source == ActivitySource.device &&
      devicePlatform == DevicePlatform.phoneSensor;

  /// End time, when the duration is known.
  DateTime? get endedAt => durationMinutes == null
      ? null
      : startedAt.add(Duration(minutes: durationMinutes!));

  factory Activity.fromJson(Map<String, dynamic> json) {
    final startedAt = DateTime.tryParse(json['startedAt'] as String? ?? '');
    if (startedAt == null) {
      // Without a start time an activity can't be placed on a day, so it
      // would silently corrupt daily totals and streaks.
      throw FormatException('Activity is missing a valid startedAt', json);
    }
    return Activity(
      id: json['id'] as String? ?? '',
      userId: json['userId'] as String? ?? '',
      type: ActivityType.fromWire(json['type'] as String?),
      source: ActivitySource.fromWire(json['source'] as String?),
      startedAt: startedAt,
      durationMinutes: (json['durationMinutes'] as num?)?.toInt(),
      distanceKm: (json['distanceKm'] as num?)?.toDouble(),
      steps: (json['steps'] as num?)?.toInt(),
      activeMinutes: (json['activeMinutes'] as num?)?.toInt(),
      calories: (json['calories'] as num?)?.toInt(),
      intensity: ActivityIntensity.fromWire(json['intensity'] as String?),
      workoutId: json['workoutId'] as String?,
      gymId: json['gymId'] as String?,
      trainerId: json['trainerId'] as String?,
      notes: json['notes'] as String?,
      devicePlatform: DevicePlatform.fromWire(
        json['devicePlatform'] as String?,
      ),
      externalId: json['externalId'] as String?,
      deviceName: json['deviceName'] as String?,
      movingSeconds: (json['movingSeconds'] as num?)?.toInt(),
      elevationGainM: (json['elevationGainM'] as num?)?.toDouble(),
      splits: [
        for (final s in (json['splits'] as List? ?? const []))
          if (s is num) s.toInt(),
      ],
      hasRoute: json['hasRoute'] == true,
      shareWith: json['shareWith'] is Map
          ? Map<String, dynamic>.from(json['shareWith'] as Map)
          : null,
    );
  }

  Map<String, dynamic> toJson() => {
    'id': id,
    'userId': userId,
    'type': type.wire,
    'source': source.wire,
    'startedAt': startedAt.toUtc().toIso8601String(),
    'durationMinutes': ?durationMinutes,
    'distanceKm': ?distanceKm,
    'steps': ?steps,
    'activeMinutes': ?activeMinutes,
    'calories': ?calories,
    'intensity': ?intensity?.wire,
    'workoutId': ?workoutId,
    'gymId': ?gymId,
    'trainerId': ?trainerId,
    'notes': ?notes,
    'devicePlatform': ?devicePlatform?.wire,
    'externalId': ?externalId,
    'deviceName': ?deviceName,
    'movingSeconds': ?movingSeconds,
    'elevationGainM': ?elevationGainM,
    if (splits.isNotEmpty) 'splits': splits,
    if (hasRoute) 'hasRoute': true,
    'shareWith': ?shareWith,
  };
}
